# Bundle plugin modules -> single .plugin.luau -> rojo binary .rbxm
param(
    [string]$OutPath = (Join-Path $env:LOCALAPPDATA "Roblox\Plugins\HazastudioClubKitPackager.rbxm")
)

$ErrorActionPreference = "Stop"
$here = $PSScriptRoot
$pluginDir = Join-Path $here "plugin"
$distDir = Join-Path $here "dist"
$rojo = Join-Path (Split-Path (Split-Path $here -Parent) -Parent) ".tools\rojo\rojo.exe"

function Transform-Requires([string]$content, [string[]]$knownModules) {
    foreach ($name in $knownModules) {
        $content = $content -replace "require\(script\.Parent\.$name\)", $name
    }
    return $content
}

function Strip-UnsupportedPluginTypes([string]$content) {
    # Roblox plugin parser rejects optional tuple/function types like `): (a, b)?`.
    $content = $content -replace '\): \(number, number, number\)\?', ')'
    $content = $content -replace ': \(\(string, number, number\) -> \(\)\)\?', ''
    return $content
}

$moduleFiles = @(
    "ClubKitManifest.luau",
    "DovetailTheme.luau",
    "RojoPathMap.luau",
    "DovetailUI.luau",
    "PackagerCore.luau",
    "SourceSyncCore.luau",
    "PackagerPanel.luau",
    "UpdaterPanel.luau"
)

$known = @()
$bundle = New-Object System.Collections.Generic.List[string]
[void]$bundle.Add("--!nocheck")
[void]$bundle.Add("-- GENERATED by build-plugin-rbxm.ps1")
[void]$bundle.Add("")

foreach ($file in $moduleFiles) {
    $path = Join-Path $pluginDir $file
    if (-not (Test-Path $path)) { Write-Error "Missing $path" }
    $modName = [System.IO.Path]::GetFileNameWithoutExtension($file)
    $content = Get-Content $path -Raw
    $content = Transform-Requires $content $known
    $content = Strip-UnsupportedPluginTypes $content
    [void]$bundle.Add("local $modName = (function()")
    [void]$bundle.Add($content.TrimEnd())
    [void]$bundle.Add("end)()")
    [void]$bundle.Add("")
    $known += $modName
}

$mainPath = Join-Path $pluginDir "HazastudioClubKit.plugin.luau"
$main = Get-Content $mainPath -Raw
$main = Transform-Requires $main $known
$main = Strip-UnsupportedPluginTypes $main
[void]$bundle.Add($main.TrimEnd())

if (-not (Test-Path $distDir)) { New-Item -ItemType Directory -Path $distDir | Out-Null }
$outPlugin = Join-Path $distDir "HazastudioClubKitPackager.plugin.luau"
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllLines($outPlugin, $bundle.ToArray(), $utf8NoBom)

$projectJson = @'
{
  "name": "HazastudioClubKitPackager",
  "tree": {
    "$path": "HazastudioClubKitPackager.plugin.luau"
  }
}
'@
[System.IO.File]::WriteAllText((Join-Path $distDir "default.project.json"), $projectJson, $utf8NoBom)

Remove-Item (Join-Path $env:LOCALAPPDATA "Roblox\Plugins\HazastudioClubKitPackager.rbxmx") -Force -ErrorAction SilentlyContinue
Remove-Item (Join-Path $env:LOCALAPPDATA "Roblox\Plugins\HazastudioClubKitPackager") -Recurse -Force -ErrorAction SilentlyContinue

Push-Location $distDir
try {
    & $rojo build default.project.json --output $OutPath
} finally {
    Pop-Location
}

$size = (Get-Item $OutPath).Length
Write-Host "Installed: $OutPath ($size bytes)"
Write-Host "Restart Roblox Studio, then check Manage Plugins"
